"""add_billing_features_channel

Revision ID: 2b3dee683c8e
Revises: 005_plan_catalog_limit
Create Date: 2026-05-04 02:05:04.816691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b3dee683c8e'
down_revision: Union[str, None] = '005_plan_catalog_limit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('billing_cycle', sa.String(length=20), nullable=False, server_default='monthly'))
    op.add_column('businesses', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('businesses', sa.Column('conversations_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('businesses', sa.Column('conversations_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('businesses', 'ai_tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'amigable'::character varying"))
    op.alter_column('businesses', 'ai_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('businesses', 'plan',
               existing_type=postgresql.ENUM('starter', 'pro', 'business', name='plan_type'),
               nullable=False,
               existing_server_default=sa.text("'starter'::plan_type"))
    op.alter_column('businesses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('businesses', 'max_phone_numbers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('businesses', 'max_conversations_per_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('500'))
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('catalog_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_catalog_source_external', table_name='catalog_items')
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_contacts_business', table_name='contacts')
    op.add_column('conversations', sa.Column('channel', sa.String(length=20), nullable=False, server_default='whatsapp'))
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('open', 'ai_handling', 'human_assigned', 'closed', name='conversation_status'),
               nullable=False,
               existing_server_default=sa.text("'ai_handling'::conversation_status"))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_logs', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'failed', 'cancelled', name='followup_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::followup_status"))
    op.alter_column('followup_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_followup_logs_pending', table_name='followup_logs')
    op.alter_column('followup_sequences', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('followup_sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_sequences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_steps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'stage',
               existing_type=postgresql.ENUM('new', 'interested', 'quoted', 'closed_won', 'closed_lost', name='lead_stage'),
               nullable=False,
               existing_server_default=sa.text("'new'::lead_stage"))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_leads_business', table_name='leads')
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('text', 'image', 'audio', 'video', 'document', 'interactive', 'template', name='message_type'),
               nullable=False,
               existing_server_default=sa.text("'text'::message_type"))
    op.alter_column('messages', 'ai_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'ai_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('messages', 'escalate_to_human',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('phone_numbers', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('phone_numbers', 'waba_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('phone_numbers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('phone_numbers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('phone_numbers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_numbers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('phone_numbers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('phone_numbers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('phone_numbers', 'waba_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('phone_numbers', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'escalate_to_human',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'ai_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('messages', 'ai_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('text', 'image', 'audio', 'video', 'document', 'interactive', 'template', name='message_type'),
               nullable=True,
               existing_server_default=sa.text("'text'::message_type"))
    op.create_index('ix_leads_business', 'leads', ['business_id', 'stage'], unique=False)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'stage',
               existing_type=postgresql.ENUM('new', 'interested', 'quoted', 'closed_won', 'closed_lost', name='lead_stage'),
               nullable=True,
               existing_server_default=sa.text("'new'::lead_stage"))
    op.alter_column('followup_steps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_sequences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_sequences', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_followup_logs_pending', 'followup_logs', ['status', 'scheduled_at'], unique=False)
    op.alter_column('followup_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followup_logs', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'failed', 'cancelled', name='followup_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::followup_status"))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('open', 'ai_handling', 'human_assigned', 'closed', name='conversation_status'),
               nullable=True,
               existing_server_default=sa.text("'ai_handling'::conversation_status"))
    op.drop_column('conversations', 'channel')
    op.create_index('ix_contacts_business', 'contacts', ['business_id'], unique=False)
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_catalog_source_external', 'catalog_items', ['business_id', 'source', 'external_id'], unique=False)
    op.alter_column('catalog_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('businesses', 'max_conversations_per_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('500'))
    op.alter_column('businesses', 'max_phone_numbers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('businesses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('businesses', 'plan',
               existing_type=postgresql.ENUM('starter', 'pro', 'business', name='plan_type'),
               nullable=True,
               existing_server_default=sa.text("'starter'::plan_type"))
    op.alter_column('businesses', 'ai_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('businesses', 'ai_tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'amigable'::character varying"))
    op.drop_column('businesses', 'conversations_reset_at')
    op.drop_column('businesses', 'conversations_this_month')
    op.drop_column('businesses', 'features')
    op.drop_column('businesses', 'billing_cycle')
    op.drop_column('businesses', 'stripe_subscription_id')
    op.drop_column('businesses', 'stripe_customer_id')
    # ### end Alembic commands ###
